/**
 * v3.cashLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import { ApiErrorsError } from '../errors/apiErrorsError';
import {
  PaymentRequestCreateRequest,
  paymentRequestCreateRequestSchema,
} from '../models/paymentRequestCreateRequest';
import {
  PaymentRequestListResponse,
  paymentRequestListResponseSchema,
} from '../models/paymentRequestListResponse';
import { string } from '../schema';
import { BaseController } from './baseController';

export class PaymentRequestController extends BaseController {
  /**
   * Creates a PaymentRequest for an accountholder_pipeline
   *
   * @param tenantId     Valid Tenant Id for request
   * @param xUserId      Valid User Id who is executing the request , this is
   *                                                           used for audit invalid user id will fail
   * @param body         The attributes of payment request
   * @return Response from the API call
   */
  async createPaymentRequest(
    tenantId: string,
    xUserId: string,
    body: PaymentRequestCreateRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PaymentRequestListResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      tenantId: [tenantId, string()],
      xUserId: [xUserId, string()],
      body: [body, paymentRequestCreateRequestSchema],
    });
    req.header('x-user-id', mapped.xUserId);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/api/tenants/${mapped.tenantId}/payment-requests`;
    req.throwOn(422, ApiErrorsError, 'Bad Request Parameter');
    return req.callAsJson(paymentRequestListResponseSchema, requestOptions);
  }
}
