/**
 * v3.cashLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { AccountHolder, accountHolderSchema } from './accountHolder';

/** Request schema for one Account Holder */
export interface AccountHolderRequest {
  /** Legal defination of an account holder */
  user?: AccountHolder;
}

export const accountHolderRequestSchema: Schema<AccountHolderRequest> = object({
  user: ['user', optional(lazy(() => accountHolderSchema))],
});
