/**
 * v3.cashLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  AccountHolderPipeline,
  accountHolderPipelineSchema,
} from './accountHolderPipeline';

/** Response schema for a single account holder pipelines */
export interface AccountHolderPipelineResponse {
  /** The details of the pipeline */
  data?: AccountHolderPipeline;
}

export const accountHolderPipelineResponseSchema: Schema<AccountHolderPipelineResponse> = object(
  { data: ['data', optional(lazy(() => accountHolderPipelineSchema))] }
);
