/**
 * v3.cashLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { AccountHolder, accountHolderSchema } from './accountHolder';

/** Response schema for a single account holders */
export interface AccountHolderResponse {
  /** Legal defination of an account holder */
  data?: AccountHolder;
}

export const accountHolderResponseSchema: Schema<AccountHolderResponse> = object(
  { data: ['data', optional(lazy(() => accountHolderSchema))] }
);
