/**
 * v3.cashLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import {
  AccountHolderPipeline,
  accountHolderPipelineSchema,
} from './accountHolderPipeline';

/** Response schema for list of account holder pipelines */
export interface AccountHolderPipelineListResponse {
  /** The details of the pipeline */
  data?: AccountHolderPipeline[];
}

export const accountHolderPipelineListResponseSchema: Schema<AccountHolderPipelineListResponse> = object(
  { data: ['data', optional(array(lazy(() => accountHolderPipelineSchema)))] }
);
