/**
 * v3.cashLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { AccountHolder, accountHolderSchema } from './accountHolder';

/** Response schema for list of account holders */
export interface AccountHolderListResponse {
  /** The account holders details */
  data?: AccountHolder[];
}

export const accountHolderListResponseSchema: Schema<AccountHolderListResponse> = object(
  { data: ['data', optional(array(lazy(() => accountHolderSchema)))] }
);
