/**
 * v3.cashLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema, string } from '../schema';

/** ApiErrorDetails */
export interface ApiErrorDetails {
  /** Field with error message */
  field: string;
  /** Error message */
  messages: string[];
}

export const apiErrorDetailsSchema: Schema<ApiErrorDetails> = object({
  field: ['field', string()],
  messages: ['messages', array(string())],
});
