/**
 * v3.cashLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { Address, addressSchema } from './address';
import { StatusEnum, statusEnumSchema } from './statusEnum';

/** Legal details of a business entity */
export interface Company {
  /** Legal physical address */
  address?: Address;
  /** Trading Name or business name which may be different from registered name */
  dbaName?: string;
  /** Trading Name or business name which may be different from registered name */
  legalName?: string;
  /** status of address */
  status?: StatusEnum;
  /** value of TIN or EIN */
  taxId?: string;
  /** Type of Tax Id TIN/EIN */
  taxIdName?: string;
}

export const companySchema: Schema<Company> = object({
  address: ['address', optional(lazy(() => addressSchema))],
  dbaName: ['dba_name', optional(string())],
  legalName: ['legal_name', optional(string())],
  status: ['status', optional(statusEnumSchema)],
  taxId: ['tax_id', optional(string())],
  taxIdName: ['tax_id_name', optional(string())],
});
