/**
 * v3.cashLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { FundAccount, fundAccountSchema } from './fundAccount';

/** Response schema for list of fund accounts */
export interface FundAccountListResponse {
  /** The details of Fund Accounts */
  data?: FundAccount[];
}

export const fundAccountListResponseSchema: Schema<FundAccountListResponse> = object(
  { data: ['data', optional(array(lazy(() => fundAccountSchema)))] }
);
