/**
 * v3.cashLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { FundAccount, fundAccountSchema } from './fundAccount';

/** Response schema for a single fund account */
export interface FundAccountResponse {
  /** Details of account from which to collect or deposit funds */
  data?: FundAccount;
}

export const fundAccountResponseSchema: Schema<FundAccountResponse> = object({
  data: ['data', optional(lazy(() => fundAccountSchema))],
});
