/**
 * v3.cashLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import {
  FundAccountConnection,
  fundAccountConnectionSchema,
} from './fundAccountConnection';
import { type1EnumSchema } from './type1Enum';

/** Details of account from which to collect or deposit funds */
export interface FundAccount {
  connections?: FundAccountConnection[];
  /** Unique name to identify the account holder */
  name: string;
  /** Unique Id of the account holder */
  ownerId: string;
  /** status of account holder, non active consumers will get blocked */
  type: Type1Enum;
}

export const fundAccountSchema: Schema<FundAccount> = object({
  connections: [
    'connections',
    optional(array(lazy(() => fundAccountConnectionSchema))),
  ],
  name: ['name', string()],
  ownerId: ['owner_id', string()],
  type: ['type', type1EnumSchema],
});
