/**
 * v3.cashLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { FundAccount, fundAccountSchema } from './fundAccount';

/** Request schema for a single fund account */
export interface FundAccountRequest {
  /** Details of account from which to collect or deposit funds */
  fundAccount?: FundAccount;
}

export const fundAccountRequestSchema: Schema<FundAccountRequest> = object({
  fundAccount: ['fund_account', optional(lazy(() => fundAccountSchema))],
});
