/**
 * v3.cashLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { FundAccount, fundAccountSchema } from './fundAccount';

/** Schema to create a payment request */
export interface PaymentRequestCreateRequest {
  /** Details of account from which to collect or deposit funds */
  data?: FundAccount;
}

export const paymentRequestCreateRequestSchema: Schema<PaymentRequestCreateRequest> = object(
  { data: ['data', optional(lazy(() => fundAccountSchema))] }
);
