/**
 * v3.cashLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { FundAccount, fundAccountSchema } from './fundAccount';

/** Response schema for list of PaymentRequests */
export interface PaymentRequestListResponse {
  /** The list of PaymentRequests */
  data?: FundAccount[];
}

export const paymentRequestListResponseSchema: Schema<PaymentRequestListResponse> = object(
  { data: ['data', optional(array(lazy(() => fundAccountSchema)))] }
);
