/**
 * v3.cashLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Status3Enum
 */
export enum Status3Enum {
  Active = 'active',
  Pending = 'pending',
}

/**
 * Schema for Status3Enum
 */
export const status3EnumSchema: Schema<Status3Enum> = stringEnum(Status3Enum);
