/**
 * v3.cashLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { User, userSchema } from './user';

/** Response schema for list of users */
export interface UserListResponse {
  /** The users details */
  data?: User[];
}

export const userListResponseSchema: Schema<UserListResponse> = object({
  data: ['data', optional(array(lazy(() => userSchema)))],
});
