/**
 * v3.cashLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { User, userSchema } from './user';

/** Response schema for one user */
export interface UserResponse {
  /** A user of the platform. This is used in context of authentication and authorization. A user can be a human or an api-client every request to the platform is invoked by a user */
  data?: User;
}

export const userResponseSchema: Schema<UserResponse> = object({
  data: ['data', optional(lazy(() => userSchema))],
});
