/**
 * v3.cashLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { User, userSchema } from './user';

/** Request schema for one user */
export interface UserRequest {
  /** A user of the platform. This is used in context of authentication and authorization. A user can be a human or an api-client every request to the platform is invoked by a user */
  user?: User;
}

export const userRequestSchema: Schema<UserRequest> = object({
  user: ['user', optional(lazy(() => userSchema))],
});
